### PR TITLE
Fixed file not found error on case sensitive drives

### PR DESCRIPTION
**Pull request by philspitler**

### CODE REVIEW

**Comment by clln** [comment]
@philspitler Hey Phil, can you tell me more about this error? I haven't encountered it before.

**Comment by philspitler** [comment]
The reference to the file on the server is:
/scripts/directives/seekBar.js

The actual file is at:
/scripts/directives/SeekBar.js

Case sensitivity matters on Linux machines and Mac's that people have modified their drives to be case sensitive which is how I figured out the issue.  On Heroku it would be a problem since they run Linux.

**Comment by clln** [comment]
Ah, okay, that makes sense. I did intend for the file to be lower case though, so `seekBar.js` to reflective the directive name. What do you think is best?

**Comment by philspitler** [comment]
haha, I was going to do that first.  I'll send a new pull request with the file name change.

**Comment by clln** [comment]
Thanks, Phil!

**Pull request closed without merging**
